### ISSUE TITLE
block classı beyaz shadow eklendi

### ISSUE THREAD

**Issue by etunadev** [crmsoft/adsvbrev#2]
global/animate.scss alt kısmına 
block classına ait kutucuklara beyaz shadow eklendi.

@mixin boxShadowWhite()
{
  -webkit-box-shadow: 0px 0px 2px 0px rgba(255,255,255,1);
  -moz-box-shadow: 0px 0px 2px 0px rgba(255,255,255,1);
  box-shadow: 0px 0px 2px 0px rgba(255,255,255,1);
}
.block,.event-schedule,.profile-about,.user-uploads
{
  @include boxShadowWhite();
}
--------------------------------------------
cover ve banner daki triangel kaldırıldı.cover un yüksekliği 200px olacak şekilde inceltildi.  

profile/profile.scss  içindeki (cover css'i)

nav.user-profile 
{
height:200px  yapıldı.
}

**Comment by crmsoft** [comment]
done

**Comment by etunadev** [comment]
.profile-about    .user-uploads   .post    
bu claslarada @mixin boxShadowWhite()   uygulayabilir misin  :)
